pub mod amount;
pub mod block_height;
pub mod bytes;
pub mod bytes_long;
pub mod common;
pub mod da_block_height;
pub mod gas_amount;
pub mod identifier;
pub mod script_execution;
pub mod tx_kind;
pub mod tx_pointer;
pub mod tx_status;
pub mod utxo_id;
pub mod word;
pub mod wrapped_int;

pub use amount::*;
pub use block_height::*;
pub use bytes::*;
pub use bytes_long::*;
pub use da_block_height::*;
pub use gas_amount::*;
pub use identifier::*;
pub use script_execution::*;
pub use tx_kind::*;
pub use tx_pointer::*;
pub use tx_status::*;
pub use utxo_id::*;
pub use word::*;

pub type BoxedError = Box<dyn std::error::Error>;
pub type BoxedResult<T> = Result<T, BoxedError>;
