{
 "title": "Surveyor - Clients",
 "tags": [ "nats-surveyor" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(nats_core_info, server_cluster)"
   },
   {
    "name": "expected",
    "query": "query_result(nats_survey_expected_count)"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_connection_count{server_cluster=~\"$cluster\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nats_core_subs_count{server_cluster=~\"$cluster\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(nats_core_total_connection_count{server_cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Connections / Second"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections",
     "type": "graph",
     "description": "Point in time view of clients connected to each Server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "current connections" }
     ],
     "targets": [
      {
       "expr": "nats_core_connection_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Current Connections %",
     "type": "graph",
     "description": "Point in time view of clients connected to each Server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "current connections" }
     ],
     "targets": [
      {
       "expr": "nats_core_connection_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Connections per second",
     "type": "graph",
     "description": "Connections received by the server in a second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "connections / sec" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_total_connection_count{server_cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Slow Consumers",
     "type": "graph",
     "description": "Slow consumers detected by each server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "slow / second" }
     ],
     "targets": [
      {
       "expr": "rate(nats_core_slow_consumer_count{server_cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Subscriptions",
     "type": "graph",
     "description": "Number of subscriptions active on the server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "subscriptions" }
     ],
     "targets": [
      {
       "expr": "nats_core_subs_count{server_cluster=~\"$cluster\"}",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Subscription Delta",
     "type": "graph",
     "description": "The difference in subscription count per minute",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "subscriptions" }
     ],
     "targets": [
      {
       "expr": "sum(delta(nats_core_subs_count{server_cluster=~\"$cluster\"}[1m]))",
       "legendFormat": "{{server_name}}"
      }
     ]
    }
   ]
  }
 ]
}