{
 "title": "Fuel-data-systems",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Consumer: Average duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(consumer_metrics_duration_milliseconds_sum[5m]) / rate(consumer_metrics_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Maximum duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by (action_type) (\n  histogram_quantile(1.0, rate(consumer_metrics_duration_milliseconds_bucket[1m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Average Packets Processed [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(consumer_metrics_packets_sum[5m]) / rate(consumer_metrics_packets_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Minimum duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min by (action_type) (\n  consumer_metrics_duration_milliseconds_bucket{le!=\"0\"} > 0\n) * 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Publisher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Publisher: Total published messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_messages_throughput)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Average message size [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(publisher_metrics_message_size_bytes_sum[5m]) / rate(publisher_metrics_message_size_bytes_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Total failed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_error_rates)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Error rates by subject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_error_rates[5m])) by (subject)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Ws Total Subs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ws_streamer_metrics_total_subscriptions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ws Average active subscriptions per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg(ws_user_active_subscriptions) by (user_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ws Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "ws_streamer_metrics_total_subscriptions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average connection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(ws_connection_duration_seconds_sum[5m]) / rate(ws_connection_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}