// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<BlockHeader>,
    #[prost(message, repeated, tag = "2")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockHeader {
    #[prost(uint32, tag = "1")]
    pub da_height: u32,
    #[prost(uint32, tag = "2")]
    pub consensus_parameters_version: u32,
    #[prost(uint32, tag = "3")]
    pub state_transition_bytecode_version: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "vec", tag = "1")]
    pub mint_asset_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub mint_amount: u64,
}
