{
 "title": "System Resources",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_load_average_1{job=\"simulator-worker\"}"
    },
    {
     "expr": "system_load_average_5{job=\"simulator-worker\"}"
    },
    {
     "expr": "system_load_average_15{job=\"simulator-worker\"}"
    }
   ]
  },
  {
   "title": "System Application CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_application_cpu_usage{job=\"simulator-worker\"}"
    }
   ]
  },
  {
   "title": "System Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "system_memory_size{job=\"simulator-worker\", type=\"system\"}"
    },
    {
     "expr": "system_memory_size{job=\"simulator-worker\", type=\"swap\"}"
    },
    {
     "expr": "system_memory_size{job=\"simulator-worker\", type=\"application\"}"
    }
   ]
  }
 ]
}