#!/bin/bash

# Set default network if not provided
NETWORK=${NETWORK:-"testnet"}
NETWORK_UPPER="$(echo "$NETWORK" | tr '[:lower:]' '[:upper:]')"

# ------------------------------
# Function to Load Environment Variables
# ------------------------------
load_env() {
    if [ -f .env ]; then
        # Read the .env file line by line, ignoring comments and empty lines
        while IFS= read -r line || [ -n "$line" ]; do
            # Skip comments and empty lines
            [[ $line =~ ^[[:space:]]*# ]] && continue
            [[ -z "$line" ]] && continue
            # Export each variable
            export "${line?}"
        done < .env
    else
        echo "Error: .env file not found. Please create a .env file with the necessary variables."
        exit 1
    fi
}

load_env

# Remove existing network-specific variables if they exist
# Create a temporary file and use it to rebuild the .env file
awk '/\n# WARNING: Everything below this line is auto-generated by set_envs.sh/{exit} {print}' .env > .env.tmp
mv .env.tmp .env

# Set and export network-specific variables
export RESERVED_NODES=$(eval echo "\$${NETWORK_UPPER}_RESERVED_NODES")
export RELAYER_V2_LISTENING_CONTRACTS=$(eval echo "\$${NETWORK_UPPER}_RELAYER_V2_LISTENING_CONTRACTS")
export RELAYER_DA_DEPLOY_HEIGHT=$(eval echo "\$${NETWORK_UPPER}_RELAYER_DA_DEPLOY_HEIGHT")
export RELAYER=$(eval echo "\$${NETWORK_UPPER}_RELAYER")
export SYNC_HEADER_BATCH_SIZE=$(eval echo "\$${NETWORK_UPPER}_SYNC_HEADER_BATCH_SIZE")
export RELAYER_LOG_PAGE_SIZE=$(eval echo "\$${NETWORK_UPPER}_RELAYER_LOG_PAGE_SIZE")
export CHAIN_CONFIG=$NETWORK
export NETWORK=$NETWORK
export USE_PUBLISHER_METRICS="$(echo "$USE_PUBLISHER_METRICS")"
export USE_ELASTIC_LOGGING="$(echo "$USE_ELASTIC_LOGGING")"

# Append network-specific variables to .env file
{
    echo -e "\n# WARNING: Everything below this line is auto-generated by set_envs.sh"
    echo "# Network-specific variables for $NETWORK"
    echo "# Last generated: $(date)"
    echo "NETWORK=$NETWORK"
    echo "RESERVED_NODES=$RESERVED_NODES"
    echo "RELAYER_V2_LISTENING_CONTRACTS=$RELAYER_V2_LISTENING_CONTRACTS"
    echo "RELAYER_DA_DEPLOY_HEIGHT=$RELAYER_DA_DEPLOY_HEIGHT"
    echo "RELAYER=$RELAYER"
    echo "SYNC_HEADER_BATCH_SIZE=$SYNC_HEADER_BATCH_SIZE"
    echo "RELAYER_LOG_PAGE_SIZE=$RELAYER_LOG_PAGE_SIZE"
    echo "CHAIN_CONFIG=$CHAIN_CONFIG"
    echo "USE_PUBLISHER_METRICS=$USE_PUBLISHER_METRICS"
    echo "USE_ELASTIC_LOGGING=$USE_ELASTIC_LOGGING"
} >> .env
