{
 "title": "Fuel Streams / Webserver Metrics",
 "tags": [
  "fuel-streams",
  "webserver"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ws Total Subs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ws_streamer_metrics_total_subscriptions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ws Average active subscriptions per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg(ws_user_active_subscriptions) by (user_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ws Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "ws_streamer_metrics_total_subscriptions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average connection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(ws_connection_duration_seconds_sum[5m]) / rate(ws_connection_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}