{
 "title": "Fuel-data-systems-publisher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Publisher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Publisher: Total Messages [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_messages_throughput)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Average Message Size [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(publisher_metrics_message_size_bytes_sum[5m]) / rate(publisher_metrics_message_size_bytes_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Total failed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_error_rates)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Error Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_error_rates[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}