{
 "title": "Fuel Publisher Metrics",
 "tags": [ "fuel-publisher" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(publisher_metrics_total_published_messages, chain_id)"
    }
   },
   {
    "name": "block_producer",
    "query": {
     "query": "label_values(publisher_metrics_total_published_messages, block_producer)"
    }
   },
   {
    "name": "subject_wildcard",
    "query": {
     "query": "label_values(publisher_metrics_published_messages_throughput, subject_wildcard)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Published Block Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(publisher_metrics_last_published_block_timestamp{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Published Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(publisher_metrics_last_published_block_height{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rates ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_error_rates{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\", error_type=~\"$error_type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Message Size Histogram (Min, Max, Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "min(publisher_metrics_message_size_bytes_bucket{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(publisher_metrics_message_size_bytes_bucket{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(publisher_metrics_message_size_bytes_sum{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"}) / avg(publisher_metrics_message_size_bytes_count{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publishing Latency (Min, Max, Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "min(publisher_metrics_block_latency_seconds_bucket{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(publisher_metrics_block_latency_seconds_bucket{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(publisher_metrics_block_latency_seconds_sum{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"}) / avg(publisher_metrics_block_latency_seconds_count{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Message Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_published_messages_throughput{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\", subject_wildcard=~\"$subject_wildcard\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Published Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_total_published_messages{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_total_subscriptions{chain_id=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Messages ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_total_failed_messages{chain_id=~\"$chain_id\", block_producer=~\"$block_producer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } }
 ]
}